"""empty message

Revision ID: 7f2049c31cd5
Revises: 
Create Date: 2021-10-07 09:04:19.304123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2049c31cd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseball',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home', sa.String(length=150), nullable=False),
    sa.Column('away', sa.String(length=150), nullable=False),
    sa.Column('spreadAway', sa.String(length=150), nullable=False),
    sa.Column('spreadHome', sa.String(length=150), nullable=False),
    sa.Column('moneyLineHome', sa.String(length=150), nullable=False),
    sa.Column('moneyLineAway', sa.String(length=150), nullable=False),
    sa.Column('scoreTotalHome', sa.Integer(), nullable=False),
    sa.Column('scoreTotalAway', sa.Integer(), nullable=False),
    sa.Column('firstFiveHome', sa.Integer(), nullable=False),
    sa.Column('firstFiveAway', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boxeo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=150), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('fighter_One', sa.String(length=150), nullable=False),
    sa.Column('fighter_Two', sa.String(length=150), nullable=False),
    sa.Column('fighter_One_Country', sa.String(length=150), nullable=False),
    sa.Column('fighter_Two_Country', sa.String(length=150), nullable=False),
    sa.Column('fighter_One_streak', sa.String(length=150), nullable=False),
    sa.Column('fighter_Two_streak', sa.String(length=150), nullable=False),
    sa.Column('fighter_One_Age', sa.Integer(), nullable=False),
    sa.Column('fighter_Two_Age', sa.Integer(), nullable=False),
    sa.Column('money_Line_One', sa.String(length=150), nullable=False),
    sa.Column('money_Line_Two', sa.String(length=150), nullable=False),
    sa.Column('winner', sa.String(length=150), nullable=False),
    sa.Column('looser', sa.String(length=150), nullable=False),
    sa.Column('finish_Type', sa.String(length=150), nullable=False),
    sa.Column('final_round', sa.Integer(), nullable=False),
    sa.Column('time_final_round', sa.String(length=100), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('fighter_One_experience', sa.String(length=100), nullable=False),
    sa.Column('fighter_Two_experience', sa.String(length=100), nullable=False),
    sa.Column('country_Fight', sa.String(length=100), nullable=False),
    sa.Column('location_Fight', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('golf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('golfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=150), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('spread', sa.String(length=150), nullable=False),
    sa.Column('money_line', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=150), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('fighter_One', sa.String(length=150), nullable=False),
    sa.Column('fighter_Two', sa.String(length=150), nullable=False),
    sa.Column('fighter_One_Country', sa.String(length=150), nullable=False),
    sa.Column('fighter_Two_Country', sa.String(length=150), nullable=False),
    sa.Column('fighter_One_streak', sa.String(length=150), nullable=False),
    sa.Column('fighter_Two_streak', sa.String(length=150), nullable=False),
    sa.Column('fighter_One_Age', sa.Integer(), nullable=False),
    sa.Column('fighter_Two_Age', sa.Integer(), nullable=False),
    sa.Column('money_Line_One', sa.String(length=150), nullable=False),
    sa.Column('money_Line_Two', sa.String(length=150), nullable=False),
    sa.Column('winner', sa.String(length=150), nullable=False),
    sa.Column('looser', sa.String(length=150), nullable=False),
    sa.Column('finish_Type', sa.String(length=150), nullable=False),
    sa.Column('final_round', sa.Integer(), nullable=False),
    sa.Column('time_final_round', sa.String(length=100), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('fighter_One_experience', sa.String(length=100), nullable=False),
    sa.Column('fighter_Two_experience', sa.String(length=100), nullable=False),
    sa.Column('country_Fight', sa.String(length=100), nullable=False),
    sa.Column('location_Fight', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nascar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('race', sa.String(length=150), nullable=False),
    sa.Column('track', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('winner', sa.String(length=150), nullable=False),
    sa.Column('money_Line', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nascar_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_driver', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=150), nullable=False),
    sa.Column('sponsor', sa.String(length=100), nullable=False),
    sa.Column('engine', sa.String(length=150), nullable=False),
    sa.Column('number_car', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nba',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home', sa.String(length=150), nullable=False),
    sa.Column('away', sa.String(length=150), nullable=False),
    sa.Column('spreadAway', sa.String(length=150), nullable=False),
    sa.Column('spreadHome', sa.String(length=150), nullable=False),
    sa.Column('moneyLineHome', sa.String(length=150), nullable=False),
    sa.Column('moneyLineAway', sa.String(length=150), nullable=False),
    sa.Column('scoreTotalHome', sa.Integer(), nullable=False),
    sa.Column('scoreTotalAway', sa.Integer(), nullable=False),
    sa.Column('scoreQ1Home', sa.Integer(), nullable=False),
    sa.Column('scoreQ1Away', sa.Integer(), nullable=False),
    sa.Column('scoreQ2Home', sa.Integer(), nullable=False),
    sa.Column('scoreQ2Away', sa.Integer(), nullable=False),
    sa.Column('scoreQ3Home', sa.Integer(), nullable=False),
    sa.Column('scoreQ3Away', sa.Integer(), nullable=False),
    sa.Column('scoreQ4Home', sa.Integer(), nullable=False),
    sa.Column('scoreQ4Away', sa.Integer(), nullable=False),
    sa.Column('scoreSecondHalf', sa.Integer(), nullable=False),
    sa.Column('scoreFirstHalf', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('url_image', sa.String(length=150), nullable=False),
    sa.Column('short_description', sa.String(length=1000), nullable=False),
    sa.Column('news_post', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nfl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home', sa.String(length=150), nullable=False),
    sa.Column('away', sa.String(length=150), nullable=False),
    sa.Column('spreadAway', sa.String(length=150), nullable=False),
    sa.Column('spreadHome', sa.String(length=150), nullable=False),
    sa.Column('moneyLineHome', sa.String(length=150), nullable=False),
    sa.Column('moneyLineAway', sa.String(length=150), nullable=False),
    sa.Column('scoreTotalHome', sa.Integer(), nullable=False),
    sa.Column('scoreTotalAway', sa.Integer(), nullable=False),
    sa.Column('scoreQ1Home', sa.Integer(), nullable=False),
    sa.Column('scoreQ1Away', sa.Integer(), nullable=False),
    sa.Column('scoreQ2Home', sa.Integer(), nullable=False),
    sa.Column('scoreQ2Away', sa.Integer(), nullable=False),
    sa.Column('scoreQ3Home', sa.Integer(), nullable=False),
    sa.Column('scoreQ3Away', sa.Integer(), nullable=False),
    sa.Column('scoreQ4Home', sa.Integer(), nullable=False),
    sa.Column('scoreQ4Away', sa.Integer(), nullable=False),
    sa.Column('scoreSecondHalf', sa.Integer(), nullable=False),
    sa.Column('scoreFirstHalf', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nhl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home', sa.String(length=150), nullable=False),
    sa.Column('away', sa.String(length=150), nullable=False),
    sa.Column('pot_Line_Home', sa.String(length=150), nullable=False),
    sa.Column('pot_Line_Away', sa.String(length=150), nullable=False),
    sa.Column('scoreTotalHome', sa.Integer(), nullable=False),
    sa.Column('scoreTotalAway', sa.Integer(), nullable=False),
    sa.Column('scoreQ1Home', sa.Integer(), nullable=False),
    sa.Column('scoreQ1Away', sa.Integer(), nullable=False),
    sa.Column('scoreQ2Home', sa.Integer(), nullable=False),
    sa.Column('scoreQ2Away', sa.Integer(), nullable=False),
    sa.Column('scoreQ3Home', sa.Integer(), nullable=False),
    sa.Column('scoreQ3Away', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nhl')
    op.drop_table('nfl')
    op.drop_table('news')
    op.drop_table('nba')
    op.drop_table('nascar_drivers')
    op.drop_table('nascar')
    op.drop_table('mma')
    op.drop_table('golfer')
    op.drop_table('golf')
    op.drop_table('boxeo')
    op.drop_table('baseball')
    # ### end Alembic commands ###
