"""empty message

Revision ID: e6a3a1ad0bbb
Revises: 592a3f321b08
Create Date: 2021-05-13 22:51:54.026292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a3a1ad0bbb'
down_revision = '592a3f321b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baseball', 'calificacionPromedio',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('baseball', 'calificacionCantidad',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('baseball', 'calificacionTotal',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('baseball', 'calificacionTotal',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('baseball', 'calificacionCantidad',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('baseball', 'calificacionPromedio',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
